name: autofix.ci
on:
  pull_request:
    branches-ignore: ["changeset-release/main"]
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: latest
          run_install: true

      - name: Run Prettier
        run: pnpm prettier

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
